---
# Source: echo-server/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-echo-server
  labels:
    app.kubernetes.io/name: echo-server
    helm.sh/chart: echo-server-0.5.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.6.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: echo-server/templates/configmap.yaml
apiVersion:  v1
kind: ConfigMap
metadata: 
  name: release-name-echo-server
data: 
    PORT: "80"
    LOGS__IGNORE__PING: "false"
    ENABLE__HOST: "true"
    ENABLE__HTTP: "true"
    ENABLE__REQUEST: "true"
    ENABLE__COOKIES: "true"
    ENABLE__ENVIRONMENT: "true"
    ENABLE__FILE: "true"
    ENABLE__HEADER: "true"
---
# Source: echo-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-echo-server
  labels:
    app.kubernetes.io/name: echo-server
    helm.sh/chart: echo-server-0.5.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.6.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: echo-server
    app.kubernetes.io/instance: release-name
---
# Source: echo-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-echo-server
  labels:
    app.kubernetes.io/name: echo-server
    helm.sh/chart: echo-server-0.5.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.6.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: echo-server
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        checksum/config: 3d1657ea4f6f0d827f80bee5bf069c060721d736b7d033cdc67246b275786cf7
      labels:
        app.kubernetes.io/name: echo-server
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-echo-server
      securityContext:
        {}
      containers:
        - name: echo-server
          securityContext:
            {}
          image: "ealen/echo-server:0.6.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: release-name-echo-server
          livenessProbe:
            httpGet:
                path: /ping
                httpHeaders:
                - name: x-echo-code
                  value: "200"
                port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
