apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test1
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: 'https://kubernetes.default.svc'
    namespace: argocd
  source:
    repoURL: https://github.com/messiahUA/temp
    path: argocd
    helm:
      values: |-
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - FailOnSharedResource=true
