apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test1
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: https://github.com/messiahUA/temp
    path: argocd
    helm:
      values: |-
        labels:
          test: test3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - FailOnSharedResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test2
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: https://github.com/messiahUA/temp
    path: echo-server
    helm:
      valueFiles:
        - test.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - FailOnSharedResource=true
